// Generated by Nora Compiler
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdarg.h>
#include <stdint.h>
#include <ctype.h>
// FILE* helpers (stdin/stdout/stderr are macros in C, wrap them as functions)
static FILE* nr_get_stdout(void) { return stdout; }
static FILE* nr_get_stderr(void) { return stderr; }
static FILE* nr_get_stdin(void)  { return stdin;  }

// --- FIBER RUNTIME (Work-Stealing) ---
#ifdef _WIN32
#include <windows.h>
#include <process.h>

#define MAX_WORKERS 16
#define DEQUE_SIZE 1024

#ifdef _MSC_VER
#define THREAD_LOCAL __declspec(thread)
#else
#define THREAD_LOCAL __thread
#endif

typedef LPVOID fiber_t;

typedef struct {
    fiber_t buffer[DEQUE_SIZE];
    volatile size_t top;
    volatile size_t bottom;
    CRITICAL_SECTION lock;
} deque_t;

deque_t deques[MAX_WORKERS];
int num_workers = 0;
THREAD_LOCAL int worker_id = -1;
fiber_t main_fibers[MAX_WORKERS];

void deque_init(deque_t* q) {
    q->top = 0; q->bottom = 0;
    InitializeCriticalSection(&q->lock);
}

void deque_push(deque_t* q, fiber_t f) {
    EnterCriticalSection(&q->lock);
    q->buffer[q->bottom % DEQUE_SIZE] = f;
    q->bottom++;
    LeaveCriticalSection(&q->lock);
}

fiber_t deque_pop(deque_t* q) {
    fiber_t f = NULL;
    EnterCriticalSection(&q->lock);
    if (q->bottom > q->top) {
        q->bottom--;
        f = q->buffer[q->bottom % DEQUE_SIZE];
    }
    LeaveCriticalSection(&q->lock);
    return f;
}


fiber_t deque_steal(deque_t* q) {
    fiber_t f = NULL;
    if (TryEnterCriticalSection(&q->lock)) {
        if (q->bottom > q->top) {
            f = q->buffer[q->top % DEQUE_SIZE];
            q->top++;
        }
        LeaveCriticalSection(&q->lock);
    }
    return f;
}

void worker_loop(void* arg) {
    worker_id = (int)(intptr_t)arg;
    main_fibers[worker_id] = ConvertThreadToFiber(NULL);

    while (1) {
        fiber_t f = deque_pop(&deques[worker_id]);
        if (!f) {
            for (int i = 0; i < num_workers; i++) {
                if (i == worker_id) continue;
                f = deque_steal(&deques[i]);
                if (f) break;
            }
        }

        if (f) {
            SwitchToFiber(f);
        } else {
            Sleep(1);
        }
    }
}

void scheduler_init() {
    SYSTEM_INFO sysinfo;
    GetSystemInfo(&sysinfo);
    num_workers = sysinfo.dwNumberOfProcessors;
    if (num_workers > MAX_WORKERS) num_workers = MAX_WORKERS;

    for (int i = 0; i < num_workers; i++) {
        deque_init(&deques[i]);
    }

    for (int i = 1; i < num_workers; i++) {
        _beginthread(worker_loop, 0, (void*)(intptr_t)i);
    }
}

void park() {
    if (worker_id >= 0) SwitchToFiber(main_fibers[worker_id]);
}

void resume(fiber_t f) {
    deque_push(&deques[worker_id >= 0 ? worker_id : 0], f);
}

int get_worker_id() { return worker_id; }

typedef struct {
    void (*fn)(void*);
    void* arg;
} spawn_data_t;

void WINAPI fiber_wrapper(LPVOID p) {
    spawn_data_t* data = (spawn_data_t*)p;
    data->fn(data->arg);
    free(data);
    park();
}

fiber_t scheduler_spawn(void* fn, void* arg) {
    spawn_data_t* data = (spawn_data_t*)malloc(sizeof(spawn_data_t));
    data->fn = (void (*)(void*))fn;
    data->arg = arg;
    fiber_t f = CreateFiber(0, (LPFIBER_START_ROUTINE)fiber_wrapper, data);
    deque_push(&deques[worker_id >= 0 ? worker_id : 0], f);
    return f;
}
#endif

// --- CHANNEL RUNTIME ---
typedef struct {
    volatile long value;
    volatile long ref_count;
} select_state_t;

typedef struct {
    fiber_t fiber;
    void* data_ptr;
    select_state_t* state;
    int index;
} waiter_t;

typedef struct {
    waiter_t buffer[DEQUE_SIZE];
    volatile size_t top;
    volatile size_t bottom;
    CRITICAL_SECTION lock;
} waiter_queue_t;

void waiter_queue_init(waiter_queue_t* q) {
    q->top = 0; q->bottom = 0;
    InitializeCriticalSection(&q->lock);
}

void waiter_queue_push(waiter_queue_t* q, fiber_t f, void* ptr, select_state_t* state, int index) {
    EnterCriticalSection(&q->lock);
    q->buffer[q->bottom % DEQUE_SIZE].fiber = f;
    q->buffer[q->bottom % DEQUE_SIZE].data_ptr = ptr;
    q->buffer[q->bottom % DEQUE_SIZE].state = state;
    if (state) InterlockedIncrement(&state->ref_count);
    q->buffer[q->bottom % DEQUE_SIZE].index = index;
    q->bottom++;
    LeaveCriticalSection(&q->lock);
}

waiter_t waiter_queue_pop(waiter_queue_t* q) {
    EnterCriticalSection(&q->lock);
    if (q->top >= q->bottom) {
        LeaveCriticalSection(&q->lock);
        return (waiter_t){0};
    }
    waiter_t w = q->buffer[q->top % DEQUE_SIZE];
    q->top++;
    LeaveCriticalSection(&q->lock);
    return w;
}

void select_state_release(select_state_t* s) {
    if (!s) return;
    if (InterlockedDecrement(&s->ref_count) == 0) {
        free(s);
    }
}

typedef struct {
    waiter_queue_t senders;
    waiter_queue_t receivers;
    void* buffer;
    int capacity;
    int size;
    int elem_size;
    int head;
    int tail;
    CRITICAL_SECTION lock;
} channel_t;

typedef struct {
    channel_t* chan;
    bool is_send;
    void* data;
} select_op_t;

channel_t* channel_make(int capacity, int elem_size) {
    channel_t* c = (channel_t*)malloc(sizeof(channel_t));
    waiter_queue_init(&c->senders);
    waiter_queue_init(&c->receivers);
    c->capacity = capacity;
    c->elem_size = elem_size;
    c->size = 0;
    c->head = 0;
    c->tail = 0;
    c->buffer = capacity > 0 ? malloc(capacity * elem_size) : NULL;
    InitializeCriticalSection(&c->lock);
    return c;
}

void channel_send(channel_t* c, void* val) {
    while (1) {
        EnterCriticalSection(&c->lock);
        waiter_t r;
        while (1) {
            r = waiter_queue_pop(&c->receivers);
            if (!r.fiber) break;
            if (r.state && r.state->value) {
                select_state_release(r.state);
                continue;
            }
            if (r.state) r.state->value = r.index;
            break;
        }
        if (r.fiber) {
            memcpy(r.data_ptr, val, c->elem_size);
            LeaveCriticalSection(&c->lock);
            resume(r.fiber);
            select_state_release(r.state);
            return;
        }
        if (c->size < c->capacity) {
            memcpy((char*)c->buffer + (c->tail * c->elem_size), val, c->elem_size);
            c->tail = (c->tail + 1) % c->capacity;
            c->size++;
            LeaveCriticalSection(&c->lock);
            return;
        }
        select_state_t* state = (select_state_t*)malloc(sizeof(select_state_t));
        state->value = 0;
        state->ref_count = 1;
        waiter_queue_push(&c->senders, GetCurrentFiber(), val, state, 1);
        LeaveCriticalSection(&c->lock);
        park();
        int result = state->value;
        select_state_release(state);
        if (result > 0) return;
    }
}

void channel_recv(channel_t* c, void* res) {
    while (1) {
        EnterCriticalSection(&c->lock);
        if (c->size > 0) {
            memcpy(res, (char*)c->buffer + (c->head * c->elem_size), c->elem_size);
            c->head = (c->head + 1) % c->capacity;
            c->size--;
            waiter_t s;
            while (1) {
                s = waiter_queue_pop(&c->senders);
                if (!s.fiber) break;
                if (s.state && s.state->value) {
                    select_state_release(s.state);
                    continue;
                }
                if (s.state) s.state->value = s.index;
                break;
            }
            if (s.fiber) {
                memcpy((char*)c->buffer + (c->tail * c->elem_size), s.data_ptr, c->elem_size);
                c->tail = (c->tail + 1) % c->capacity;
                c->size++;
                LeaveCriticalSection(&c->lock);
                resume(s.fiber);
            } else {
                LeaveCriticalSection(&c->lock);
            }
            return;
        }
        waiter_t s;
        while (1) {
            s = waiter_queue_pop(&c->senders);
            if (!s.fiber) break;
            if (s.state && s.state->value) {
                select_state_release(s.state);
                continue;
            }
            if (s.state) s.state->value = s.index;
            break;
        }
        if (s.fiber) {
            memcpy(res, s.data_ptr, c->elem_size);
            LeaveCriticalSection(&c->lock);
            resume(s.fiber);
            select_state_release(s.state);
            return;
        }
        select_state_t* state = (select_state_t*)malloc(sizeof(select_state_t));
        state->value = 0;
        state->ref_count = 1;
        waiter_queue_push(&c->receivers, GetCurrentFiber(), res, state, 1);
        LeaveCriticalSection(&c->lock);
        park();
        int result = state->value;
        select_state_release(state);
        if (result > 0) return;
    }
}

int channel_select(select_op_t* ops, int count, bool has_default) {
    while (1) {
        for (int i = 0; i < count; i++) {
            channel_t* c = ops[i].chan;
            EnterCriticalSection(&c->lock);
            if (ops[i].is_send) {
                waiter_t r;
                while (1) {
                    r = waiter_queue_pop(&c->receivers);
                    if (!r.fiber) break;
                    if (r.state && r.state->value) {
                        select_state_release(r.state);
                        continue;
                    }
                    if (r.state) r.state->value = r.index;
                    break;
                }
                if (r.fiber) {
                    memcpy(r.data_ptr, ops[i].data, c->elem_size);
                    LeaveCriticalSection(&c->lock);
                    resume(r.fiber);
                    select_state_release(r.state);
                    return i;
                }
                if (c->size < c->capacity) {
                    memcpy((char*)c->buffer + (c->tail * c->elem_size), ops[i].data, c->elem_size);
                    c->tail = (c->tail + 1) % c->capacity;
                    c->size++;
                    LeaveCriticalSection(&c->lock);
                    return i;
                }
            } else {
                if (c->size > 0) {
                    memcpy(ops[i].data, (char*)c->buffer + (c->head * c->elem_size), c->elem_size);
                    c->head = (c->head + 1) % c->capacity;
                    c->size--;
                    waiter_t s;
                    while (1) {
                        s = waiter_queue_pop(&c->senders);
                        if (!s.fiber) break;
                        if (s.state && s.state->value) {
                            select_state_release(s.state);
                            continue;
                        }
                        if (s.state) s.state->value = s.index;
                        break;
                    }
                    if (s.fiber) {
                        memcpy((char*)c->buffer + (c->tail * c->elem_size), s.data_ptr, c->elem_size);
                        c->tail = (c->tail + 1) % c->capacity;
                        c->size++;
                        LeaveCriticalSection(&c->lock);
                        resume(s.fiber);
                        select_state_release(s.state);
                    } else {
                        LeaveCriticalSection(&c->lock);
                    }
                    return i;
                }
                waiter_t s;
                while (1) {
                    s = waiter_queue_pop(&c->senders);
                    if (!s.fiber) break;
                    if (s.state && s.state->value) {
                        select_state_release(s.state);
                        continue;
                    }
                    if (s.state) s.state->value = s.index;
                    break;
                }
                if (s.fiber) {
                    memcpy(ops[i].data, s.data_ptr, c->elem_size);
                    LeaveCriticalSection(&c->lock);
                    resume(s.fiber);
                    select_state_release(s.state);
                    return i;
                }
            }
            LeaveCriticalSection(&c->lock);
        }
        if (has_default) return -1;
        select_state_t* state = (select_state_t*)malloc(sizeof(select_state_t));
        state->value = 0;
        state->ref_count = 1; // 1 for the current fiber
        fiber_t self = GetCurrentFiber();
        for (int i = 0; i < count; i++) {
            channel_t* c = ops[i].chan;
            EnterCriticalSection(&c->lock);
            if (ops[i].is_send) waiter_queue_push(&c->senders, self, ops[i].data, state, i + 1);
            else waiter_queue_push(&c->receivers, self, ops[i].data, state, i + 1);
            LeaveCriticalSection(&c->lock);
        }
        park();
        int result = state->value;
        select_state_release(state);
        if (result > 0) return result - 1;
    }
}
// --- COLLECTION RUNTIME ---
void* array_make(int count, int elem_size, ...) {
    void* arr = malloc(count * elem_size + 8);
    ((int*)arr)[0] = count;
    ((int*)arr)[1] = elem_size;
    void* data = (char*)arr + 8;
    
    va_list args;
    va_start(args, elem_size);
    for (int i = 0; i < count; i++) {
        if (elem_size == sizeof(int)) {
            int val = va_arg(args, int);
            memcpy((char*)data + (i * elem_size), &val, elem_size);
        } else if (elem_size == sizeof(double)) {
            double val = va_arg(args, double);
            memcpy((char*)data + (i * elem_size), &val, elem_size);
        } else {
            void* val = va_arg(args, void*);
            memcpy((char*)data + (i * elem_size), &val, elem_size);
        }
    }
    va_end(args);
    return data;
}
bool array_contains(void* data, void* val) {
    if (!data) return false;
    int count = ((int*)((char*)data - 8))[0];
    int elem_size = ((int*)((char*)data - 8))[1];
    for (int i = 0; i < count; i++) {
        if (memcmp((char*)data + (i * elem_size), &val, elem_size) == 0) return true;
    }
    return false;
}
void* array_data(void* data) { return data; }
int array_count(void* data) { return data ? ((int*)((char*)data - 8))[0] : 0; }
// --- HASH MAP RUNTIME ---
typedef struct {
    void* key;
    void* val;
    bool occupied;
} MapEntry;

typedef struct {
    MapEntry* entries;
    int capacity;
    int size;
    int key_size;
    int val_size;
    bool is_str_key;
} HashMap;

uint32_t map_hash(HashMap* m, void* key) {
    uint32_t hash = 2166136261u;
    unsigned char* p;
    int len;
    if (m->is_str_key) {
        p = (unsigned char*)(*(char**)key);
        len = strlen((char*)p);
    } else {
        p = (unsigned char*)key;
        len = m->key_size;
    }
    for (int i = 0; i < len; i++) {
        hash = (hash ^ p[i]) * 16777619;
    }
    return hash;
}

bool map_key_eq(HashMap* m, void* k1, void* k2) {
    if (m->is_str_key) {
        return strcmp(*(char**)k1, *(char**)k2) == 0;
    }
    return memcmp(k1, k2, m->key_size) == 0;
}

void* map_make(int key_size, int val_size, bool is_str_key) {
    HashMap* m = malloc(sizeof(HashMap));
    m->capacity = 16;
    m->size = 0;
    m->key_size = key_size;
    m->val_size = val_size;
    m->is_str_key = is_str_key;
    m->entries = calloc(m->capacity, sizeof(MapEntry));
    return m;
}

void map_set(void* _m, void* key, void* val) {
    HashMap* m = (HashMap*)_m;
    if (m->size >= m->capacity * 0.7) {
        // Resize
        int old_cap = m->capacity;
        MapEntry* old_entries = m->entries;
        m->capacity *= 2;
        m->entries = calloc(m->capacity, sizeof(MapEntry));
        m->size = 0;
        for (int i = 0; i < old_cap; i++) {
            if (old_entries[i].occupied) {
                map_set(m, old_entries[i].key, old_entries[i].val);
                if (m->is_str_key) free(*(char**)old_entries[i].key);
                free(old_entries[i].key);
                free(old_entries[i].val);
            }
        }
        free(old_entries);
    }

    uint32_t h = map_hash(m, key) % m->capacity;
    while (m->entries[h].occupied) {
        if (map_key_eq(m, m->entries[h].key, key)) {
            memcpy(m->entries[h].val, val, m->val_size);
            return;
        }
        h = (h + 1) % m->capacity;
    }

    m->entries[h].key = malloc(m->key_size);
    memcpy(m->entries[h].key, key, m->key_size);
    if (m->is_str_key) {
        char* original = *(char**)key;
        char* copy = malloc(strlen(original) + 1);
        strcpy(copy, original);
        *(char**)m->entries[h].key = copy;
    }
    m->entries[h].val = malloc(m->val_size);
    memcpy(m->entries[h].val, val, m->val_size);
    m->entries[h].occupied = true;
    m->size++;
}

void* map_get(void* _m, void* key) {
    HashMap* m = (HashMap*)_m;
    if (!m) return NULL;
    uint32_t h = map_hash(m, key) % m->capacity;
    int start = h;
    while (m->entries[h].occupied) {
        if (map_key_eq(m, m->entries[h].key, key)) {
            return m->entries[h].val;
        }
        h = (h + 1) % m->capacity;
        if (h == start) break;
    }
    return NULL;
}

bool map_contains(void* _m, void* key) {
    return map_get(_m, key) != NULL;
}

void map_free(void* _m) {
    HashMap* m = (HashMap*)_m;
    if (!m) return;
    for (int i = 0; i < m->capacity; i++) {
        if (m->entries[i].occupied) {
            if (m->is_str_key) free(*(char**)m->entries[i].key);
            free(m->entries[i].key);
            free(m->entries[i].val);
        }
    }
    free(m->entries);
    free(m);
}

void* array_bounds_check(void* arr, int index, const char* file, int line) {
    if (!arr) {
        fprintf(stderr, "Panic: null array access at %s:%d\n", file, line);
        exit(1);
    }
    int count = ((int*)arr)[0];
    int elem_size = ((int*)arr)[1];
    if (index < 0 || index >= count) {
        fprintf(stderr, "Panic: array index out of bounds: %d (length %d) at %s:%d\n", index, count, file, line);
        exit(1);
    }
    return (char*)arr + 8 + (index * elem_size);
}
void nr_panic(const char* msg, const char* file, int line) {
    fprintf(stderr, "Panic: %s at %s:%d\n", msg, file, line);
    exit(1);
}

int WINAPI nr_main();
void WINAPI print();
void WINAPI println();
void WINAPI eprint();
void WINAPI eprintln();
void WINAPI scan();
void WINAPI scanln();
char* WINAPI format_int(int n);
char* WINAPI format_float(double f);
char* WINAPI format_bool(bool b);
char* WINAPI read_line();
int WINAPI read_char();
int WINAPI read_int();
char* WINAPI scan_str();
int WINAPI seek_set();
int WINAPI seek_cur();
int WINAPI seek_end();
void* WINAPI open(char* path, char* mode);
void WINAPI close(void* f);
void WINAPI write_to(void* f, char* s);
void WINAPI writeln_to(void* f, char* s);
void WINAPI write_char_to(void* f, int c);
char* WINAPI read_line_from(void* f);
bool WINAPI is_eof(void* f);
bool WINAPI has_error(void* f);
void WINAPI flush(void* f);
void WINAPI flush_stdout();
bool WINAPI seek(void* f, int offset, int whence);
int WINAPI tell(void* f);
void WINAPI rewind_file(void* f);
void WINAPI hello();



int WINAPI nr_main() {
    printf("Verification Project Starting...\n");;
    hello();
    printf("Verification Complete.\n");;
    return 0;
}



























char* WINAPI format_int(int n) {
    unsigned char* buf = ({ int _n = 32; void* _p = malloc(_n * sizeof(unsigned char) + 8); ((int*)_p)[0] = _n; ((int*)_p)[1] = sizeof(unsigned char); unsigned char* _data = (unsigned char*)((char*)_p + 8); memset(_data, 0, _n * sizeof(unsigned char)); _data; });
    snprintf(buf, 32, "%d", n);
    { unsigned char* _ret = buf;
    return _ret; }
}

char* WINAPI format_float(double f) {
    unsigned char* buf = ({ int _n = 64; void* _p = malloc(_n * sizeof(unsigned char) + 8); ((int*)_p)[0] = _n; ((int*)_p)[1] = sizeof(unsigned char); unsigned char* _data = (unsigned char*)((char*)_p + 8); memset(_data, 0, _n * sizeof(unsigned char)); _data; });
    snprintf(buf, 64, "%g", f);
    { unsigned char* _ret = buf;
    return _ret; }
}

char* WINAPI format_bool(bool b) {
    if (b) {
    { char* _ret = "true";
    return _ret; }
    };
    { char* _ret = "false";
    return _ret; }
}

char* WINAPI read_line() {
    unsigned char* buf = ({ int _n = 4096; void* _p = malloc(_n * sizeof(unsigned char) + 8); ((int*)_p)[0] = _n; ((int*)_p)[1] = sizeof(unsigned char); unsigned char* _data = (unsigned char*)((char*)_p + 8); memset(_data, 0, _n * sizeof(unsigned char)); _data; });
    int i = 0;
    int c = getchar();
    while ((((c != 10) && (c != -1)) && (i < 4095))) {
    (*({ unsigned char* _p = buf; int _idx = i; int _n = ((int*)((char*)_p - 8))[0]; if (_idx < 0 || _idx >= _n) nr_panic("index out of bounds", "io.nr", 82); &(_p[_idx]); })) = c;
    i = (i + 1);
    c = getchar();
}
    // End of life for stack var 'c'
    (*({ unsigned char* _p = buf; int _idx = i; int _n = ((int*)((char*)_p - 8))[0]; if (_idx < 0 || _idx >= _n) nr_panic("index out of bounds", "io.nr", 86); &(_p[_idx]); })) = 0;
    // End of life for stack var 'i'
    { unsigned char* _ret = buf;
    return _ret; }
}

int WINAPI read_char() {
    { int _ret = getchar();
    return _ret; }
}

int WINAPI read_int() {
    int c = getchar();
    int result = 0;
    bool negative = false;
    while (((((c == 32) || (c == 10)) || (c == 9)) || (c == 13))) {
    c = getchar();
}
    if ((c == 45)) {
    negative = true;
    c = getchar();
    };
    while (((c >= 48) && (c <= 57))) {
    result = ((result * 10) + (c - 48));
    c = getchar();
}
    // End of life for stack var 'c'
    if (negative) {
    { int _ret = (0 - result);
    return _ret; }
    };
    // End of life for stack var 'negative'
    { int _ret = result;
    return _ret; }
}

char* WINAPI scan_str() {
    unsigned char* buf = ({ int _n = 4096; void* _p = malloc(_n * sizeof(unsigned char) + 8); ((int*)_p)[0] = _n; ((int*)_p)[1] = sizeof(unsigned char); unsigned char* _data = (unsigned char*)((char*)_p + 8); memset(_data, 0, _n * sizeof(unsigned char)); _data; });
    int i = 0;
    int c = getchar();
    while (((((c == 32) || (c == 10)) || (c == 9)) || (c == 13))) {
    c = getchar();
}
    while (((((((c != 32) && (c != 10)) && (c != 9)) && (c != 13)) && (c != -1)) && (i < 4095))) {
    (*({ unsigned char* _p = buf; int _idx = i; int _n = ((int*)((char*)_p - 8))[0]; if (_idx < 0 || _idx >= _n) nr_panic("index out of bounds", "io.nr", 133); &(_p[_idx]); })) = c;
    i = (i + 1);
    c = getchar();
}
    // End of life for stack var 'c'
    (*({ unsigned char* _p = buf; int _idx = i; int _n = ((int*)((char*)_p - 8))[0]; if (_idx < 0 || _idx >= _n) nr_panic("index out of bounds", "io.nr", 137); &(_p[_idx]); })) = 0;
    // End of life for stack var 'i'
    { unsigned char* _ret = buf;
    return _ret; }
}

int WINAPI seek_set() {
    { int _ret = 0;
    return _ret; }
}

int WINAPI seek_cur() {
    { int _ret = 1;
    return _ret; }
}

int WINAPI seek_end() {
    { int _ret = 2;
    return _ret; }
}

void* WINAPI open(char* path, char* mode) {
    { void* _ret = fopen(path, mode);
    return _ret; }
}

void WINAPI close(void* f) {
    fclose(f);
}

void WINAPI write_to(void* f, char* s) {
    fputs(s, f);
}

void WINAPI writeln_to(void* f, char* s) {
    fputs(s, f);
    fputc(10, f);
}

void WINAPI write_char_to(void* f, int c) {
    fputc(c, f);
}

char* WINAPI read_line_from(void* f) {
    if (is_eof(f)) {
    { void* _ret = NULL;
    return _ret; }
    };
    unsigned char* buf = ({ int _n = 4096; void* _p = malloc(_n * sizeof(unsigned char) + 8); ((int*)_p)[0] = _n; ((int*)_p)[1] = sizeof(unsigned char); unsigned char* _data = (unsigned char*)((char*)_p + 8); memset(_data, 0, _n * sizeof(unsigned char)); _data; });
    int i = 0;
    int c = fgetc(f);
    while ((((c != 10) && (c != -1)) && (i < 4095))) {
    (*({ unsigned char* _p = buf; int _idx = i; int _n = ((int*)((char*)_p - 8))[0]; if (_idx < 0 || _idx >= _n) nr_panic("index out of bounds", "io.nr", 185); &(_p[_idx]); })) = c;
    i = (i + 1);
    c = fgetc(f);
}
    if (((i == 0) && (c == -1))) {
    { void* _ret = NULL;
    return _ret; }
    };
    // End of life for stack var 'c'
    (*({ unsigned char* _p = buf; int _idx = i; int _n = ((int*)((char*)_p - 8))[0]; if (_idx < 0 || _idx >= _n) nr_panic("index out of bounds", "io.nr", 192); &(_p[_idx]); })) = 0;
    // End of life for stack var 'i'
    { unsigned char* _ret = buf;
    return _ret; }
}

bool WINAPI is_eof(void* f) {
    { bool _ret = (feof(f) != 0);
    return _ret; }
}

bool WINAPI has_error(void* f) {
    { bool _ret = (ferror(f) != 0);
    return _ret; }
}

void WINAPI flush(void* f) {
    fflush(f);
}

void WINAPI flush_stdout() {
    fflush(nr_get_stdout());
}

bool WINAPI seek(void* f, int offset, int whence) {
    { bool _ret = (fseek(f, offset, whence) == 0);
    return _ret; }
}

int WINAPI tell(void* f) {
    { int _ret = ftell(f);
    return _ret; }
}

void WINAPI rewind_file(void* f) {
    rewind(f);
}



void WINAPI hello() {
    printf("Hello from test_lib!\n");;
}

// --- BOOTSTRAP ---
void WINAPI main_fiber_wrapper(LPVOID param) {
    nr_main();
    exit(0);
}

int main() {
    scheduler_init();
    scheduler_spawn((void*)main_fiber_wrapper, NULL);
    worker_loop((void*)0);
    return 0;
}
