package api

// CallRequest represents a function call being processed by a macro.
type CallRequest struct {
	FunctionName string            `json:"function_name"`
	Arguments    []CallArgumentDTO `json:"arguments"`
}

// CallArgumentDTO represents a single argument in a function call.
type CallArgumentDTO struct {
	Value string `json:"value_raw"`
	Type  string `json:"type_name"` // The type resolved by the semantic analyzer
}

// CallResponse represents the code generated by a call-site macro.
type CallResponse struct {
	ReplacementCode string `json:"replacement_code"` // C code to replace the call
	Error           string `json:"error,omitempty"`
}
