package codegen

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/nora-language/nora/pkg/hir"
	"github.com/nora-language/nora/pkg/hir/optimize"
	"github.com/nora-language/nora/pkg/parser/ast"
	"github.com/nora-language/nora/pkg/plugin"
	"github.com/nora-language/nora/pkg/semantic"
	"github.com/nora-language/nora/pkg/topology"
	"github.com/nora-language/nora/pkg/types"
)

type Generator struct {
	Program          *ast.Program
	SemanticInfo     *semantic.SemanticInfo
	Solver           *topology.Solver
	PluginMgr        *plugin.PluginManager
	Target           string
	EnableDebug      bool
	DebugMemory      bool
	DebugSemantic    bool
	NoStdlib         bool
	NoTempWrap       bool
	InMoveOperator   bool
	InCallExpression bool
	MultiFileMode    bool
	TargetIsValue    bool

	// Internal State
	buf             *bytes.Buffer
	Functions       map[string]*semantic.Symbol
	Structs         map[string]*types.StructType
	SumTypes        map[string]*types.SumType
	Protocols       map[string]*types.ProtocolType
	Globals         map[string]*semantic.Symbol
	GlobalInits     []*ast.VarStatement
	SpawnWrappers   []string
	SpawnStructs    []string
	spawnCounter    int
	ScopeWaitgroups []string
	scopeCounter    int

	// Loop states
	loopCounter int

	currentFile string
	currentLine int

	CurrentFunc     *semantic.Symbol
	CurrentLambda   *ast.LambdaExpression
	AutoDropMethods map[string]types.NRType
	AutoEqMethods   map[string]types.NRType
	VTables         map[string]VTableInstance

	CurrentBlock     *ast.BlockStatement
	CurrentStmtIndex int

	eraseCache       map[string]types.NRType
	NativeHeaders    []string
	GeneratedLambdas map[string]bool

	// String Literals
	StringLiterals map[string]string // maps string content to global variable name
	hirProg        *hir.Program
}

type VTableInstance struct {
	Type     types.NRType
	Protocol *types.ProtocolType
}

func NewGenerator(prog *ast.Program, sem *semantic.SemanticInfo, solver *topology.Solver, pluginMgr *plugin.PluginManager, nativeHeaders []string) *Generator {
	return &Generator{
		Program:          prog,
		SemanticInfo:     sem,
		Solver:           solver,
		PluginMgr:        pluginMgr,
		Functions:        make(map[string]*semantic.Symbol),
		Structs:          make(map[string]*types.StructType),
		SumTypes:         make(map[string]*types.SumType),
		Protocols:        make(map[string]*types.ProtocolType),
		Globals:          make(map[string]*semantic.Symbol),
		buf:              new(bytes.Buffer),
		currentLine:      -1,
		AutoDropMethods:  make(map[string]types.NRType),
		AutoEqMethods:    make(map[string]types.NRType),
		VTables:          make(map[string]VTableInstance),
		eraseCache:       make(map[string]types.NRType),
		NativeHeaders:    nativeHeaders,
		StringLiterals:   make(map[string]string),
		GeneratedLambdas: make(map[string]bool),
	}
}

func (g *Generator) emitRuntime() {
	if g.NoStdlib {
		g.emit("#include <stdint.h>")
		g.emit("#include <stdbool.h>")
		g.emit("#include <stddef.h>")
		g.emit("")
	} else {
		for _, header := range g.NativeHeaders {
			g.emit(fmt.Sprintf("#include \"%s\"", header))
		}
		g.emit("")
	}

	if g.DebugMemory {
		g.emit("#define NR_DEBUG_MEM 1")
	} else {
		g.emit("#define NR_DEBUG_MEM 0")
	}
	g.emit("")
	g.emit("#define malloc nr_malloc")
	g.emit("#define free nr_free")
	g.emit("#define strdup nr_strdup")
}

func (g *Generator) emitYieldCheckpoint() {
	if !g.NoStdlib {
		g.emit("    NR_COOPERATIVE_YIELD_CHECKPOINT();")
	}
}

func (g *Generator) Generate() (string, error) {
	g.buf.Reset()
	// 1. Collect all definitions
	g.collectDefinitions()

	// Lower AST to HIR
	if g.hirProg == nil {
		lowerer := hir.NewLowerer(g.SemanticInfo, g.Solver)
		lowerer.DebugLog = g.DebugSemantic
		prog := lowerer.LowerProgram(g.Program)
		opt := optimize.NewOptimizer(g.SemanticInfo)
		g.hirProg = opt.OptimizeProgram(prog)
	}
	hirProg := g.hirProg
	hirFuncs := make(map[string]*hir.Function)
	for _, hf := range hirProg.Functions {
		hirFuncs[g.mangleName(hf.FuncSymbol)] = hf
	}

	// 2. Emit Header
	g.emit("// Generated by Nora Compiler")
	g.emit("")

	// Emit native headers requested by dependencies
	for _, hdr := range g.NativeHeaders {
		g.emit(fmt.Sprintf("#include \"%s\"", hdr))
	}
	g.emit("")

	// 4. Emit Runtime Components
	g.emitRuntime()

	// 5. Emit Type Forward Declarations
	g.emitForwardDeclarations()

	// 7. Emit Protocol Definitions
	g.emitProtocolDefs()

	// 6. Emit Topologically Sorted Type Definitions (Combined Struct and Sum Types)
	g.emitCombinedTypeDefs()

	// Emit Lambda Environment Struct Definitions
	g.emitLambdaEnvDefs()

	// 8. Emit Prototypes
	for _, file := range g.Program.Files {
		g.emitExternPrototypes(file)
	}
	g.emitPrototypes()

	// 9. Emit Global Definitions
	g.emitGlobalDefs()

	// 10. Generate Function Definitions (but don't emit yet)
	funcBuf := new(bytes.Buffer)
	mainBuf := g.buf
	g.buf = funcBuf

	for _, name := range g.sortedFunctionNames() {
		sym := g.Functions[name]
		if sym.DefNode == nil {
			continue
		}
		fn, ok := sym.DefNode.(*ast.FunctionStatement)
		if !ok || ast.GetAttribute(fn.Attributes, "macro") != nil || fn.Body == nil {
			continue
		}
		if hf, ok := hirFuncs[name]; ok {
			g.genHIRFunction(hf)
		} else {
			if fnStmt, ok := sym.DefNode.(*ast.FunctionStatement); ok && len(fnStmt.TypeParameters) > 0 {
				// 
			}
			g.genFunction(sym, fn)
		}
	}

	// Compile lowered lambda functions
	for _, hf := range hirProg.Functions {
		if hf.LambdaExpr != nil {
			g.genHIRFunction(hf)
		}
	}
	// 11b. Emit Auto-Generated Drop Methods (to handle recursive structures)
	g.emitAutoDropMethods()

	// Emit Lambda Environment Drop Functions
	g.emitLambdaEnvDrops()

	// 11d. Emit Auto-Generated Equality Methods
	g.emitAutoEqMethods()

	// 11c. Emit Global Initializers
	g.emitGlobalInits()

	// 12. Emit Main Wrapper
	mainName := "main" // Default Nora main
	for _, sym := range g.Functions {
		if sym.Name == "main" {
			mainName = g.mangleName(sym)
			break
		}
	}
	platform := g.GetTarget()
	g.emit(platform.GetMainWrapper(mainName))

	// Restore main buffer
	g.buf = mainBuf

	// [NEW] Now that ALL generations have finished, g.StringLiterals is 100% complete!
	// We can safely emit all collected string literals here:
	g.emitStringLiterals()

	// [NEW] Emit Prototypes for Auto-Generated Drop Methods
	g.emitAutoDropPrototypes()
	// [NEW] Emit Prototypes for Auto-Generated Equality Methods
	g.emitAutoEqPrototypes()

	g.emitVTables()

	// Emit Global Cleanups
	g.emitGlobalCleanups()

	// 9b. Emit Spawn Wrappers (now populated)
	for _, s := range g.SpawnStructs {
		g.emit(s)
	}
	for _, s := range g.SpawnWrappers {
		g.emit(s)
	}

	// Finally, append all the compiled functions, drop methods, global inits, and main wrapper!
	g.buf.Write(funcBuf.Bytes())

	return g.buf.String(), nil
}

func (g *Generator) eraseType(t types.NRType) types.NRType {
	if t == nil {
		return nil
	}
	if t.Name() == "str" || t.Name() == "ptr" {
		return types.Ptr
	}
	switch pt := t.(type) {
	case *types.PointerType:
		erasedBase := g.eraseType(pt.Base)
		if st, ok := erasedBase.(*types.StructType); ok && st.BaseType != nil {
			return &types.PointerType{
				Base:    erasedBase,
				IsArray: pt.IsArray,
				Leased:  pt.Leased,
				Kind:    pt.Kind,
			}
		}
		if sum, ok := erasedBase.(*types.SumType); ok && sum.BaseType != nil {
			return &types.PointerType{
				Base:    erasedBase,
				IsArray: pt.IsArray,
				Leased:  pt.Leased,
				Kind:    pt.Kind,
			}
		}
		if fn, ok := erasedBase.(*types.FunctionType); ok {
			return &types.PointerType{
				Base:    fn,
				IsArray: pt.IsArray,
				Leased:  pt.Leased,
				Kind:    pt.Kind,
			}
		}
		return types.Ptr
	case *types.ListType:
		return &types.ListType{
			ElementType: g.eraseType(pt.ElementType),
		}
	case *types.ChanType:
		return &types.ChanType{
			Elem: g.eraseType(pt.Elem),
		}
	case *types.StructType:
		if pt.BaseType != nil && len(pt.TypeArgs) > 0 {
			allPointerLike := true
			for _, arg := range pt.TypeArgs {
				if !types.IsPointerLike(arg) || types.IsOwnedType(arg) {
					allPointerLike = false
					break
				}
			}
			if allPointerLike {
				if erasedName := g.getErasedTypeName(pt); erasedName != "" {
					if cached, ok := g.eraseCache[erasedName]; ok {
						return cached
					}

					erasedArgs := make([]types.NRType, len(pt.TypeArgs))
					for i := range pt.TypeArgs {
						erasedArgs[i] = types.Ptr
					}
					placeholder := &types.StructType{
						TypeName:   erasedName,
						BaseType:   pt.BaseType,
						TypeParams: pt.TypeParams,
						TypeArgs:   erasedArgs,
						Methods:    make(map[string]types.NRType),
						FieldNames: append([]string(nil), pt.FieldNames...),
					}
					g.eraseCache[erasedName] = placeholder

					erasedFields := make(map[string]types.NRType)
					placeholder.Fields = erasedFields
					for fName, fType := range pt.Fields {
						erasedFields[fName] = g.eraseType(fType)
					}
					return placeholder
				}
			}
		}
	case *types.SumType:
		if pt.BaseType != nil && len(pt.TypeArgs) > 0 {
			allPointerLike := true
			for _, arg := range pt.TypeArgs {
				if !types.IsPointerLike(arg) || types.IsOwnedType(arg) {
					allPointerLike = false
					break
				}
			}
			if allPointerLike {
				if erasedName := g.getErasedTypeName(pt); erasedName != "" {
					if cached, ok := g.eraseCache[erasedName]; ok {
						return cached
					}

					erasedArgs := make([]types.NRType, len(pt.TypeArgs))
					for i := range pt.TypeArgs {
						erasedArgs[i] = types.Ptr
					}
					placeholder := &types.SumType{
						TypeName:   erasedName,
						BaseType:   pt.BaseType,
						TypeParams: pt.TypeParams,
						TypeArgs:   erasedArgs,
						Methods:    make(map[string]types.NRType),
					}
					g.eraseCache[erasedName] = placeholder

					erasedVariants := make(map[string]*types.Variant)
					placeholder.Variants = erasedVariants
					for vName, variant := range pt.Variants {
						erasedVar := &types.Variant{
							Name:       variant.Name,
							Tag:        variant.Tag,
							Fields:     make(map[string]types.NRType),
							FieldNames: append([]string(nil), variant.FieldNames...),
						}
						for fName, fType := range variant.Fields {
							erasedVar.Fields[fName] = g.eraseType(fType)
						}
						erasedVariants[vName] = erasedVar
					}
					return placeholder
				}
			}
		}
	}
	return t
}

func (g *Generator) isTypeNamePointerLike(name string) bool {
	name = strings.TrimPrefix(name, "@")
	name = strings.TrimPrefix(name, "#")
	name = strings.TrimPrefix(name, "&")
	name = strings.TrimPrefix(name, "*")
	return name == "ptr" || name == "str" || strings.HasSuffix(name, "*") || strings.HasPrefix(name, "ptr") || strings.HasPrefix(name, "str") || strings.Contains(name, "_ptr") || strings.Contains(name, "_str") || strings.Contains(name, "ptr_") || strings.Contains(name, "str_")
}

func (g *Generator) findDefSymbol(name string) *semantic.Symbol {
	for id, sym := range g.SemanticInfo.Defs {
		if id != nil && id.Value == name {
			return sym
		}
		if sym != nil && sym.Name == name {
			return sym
		}
	}
	for _, subMap := range g.SemanticInfo.MethodSymbols {
		for _, sym := range subMap {
			if sym != nil && sym.Name == name {
				return sym
			}
		}
	}
	return nil
}

func (g *Generator) collectDefinitions() {
	for _, file := range g.Program.Files {
		for _, stmt := range file.Statements {
			switch s := stmt.(type) {
			case *ast.FunctionStatement:
				if len(s.TypeParameters) > 0 || s.IsGenericTemplate {
					continue
				}
				sym := g.SemanticInfo.Defs[s.Name]
				if sym != nil {
					g.Functions[g.mangleName(sym)] = sym
				}
			case *ast.TypeStatement:
				if len(s.TypeParameters) > 0 {
					continue
				}
				sym := g.SemanticInfo.Defs[s.Name]
				if sym == nil {
					if g.DebugSemantic {
						fmt.Printf("[DEBUG-collectDefinitions] Name=%s NOT FOUND\n", s.Name.Value)
					}
					continue
				}
				t := sym.Type
				if g.DebugSemantic {
					fmt.Printf("[DEBUG-collectDefinitions] Name=%s, Type=%T\n", s.Name.Value, t)
				}
				mangled := g.mangleName(sym)
				if st, ok := t.(*types.StructType); ok {
					if len(st.TypeParams) > 0 {
						continue
					}
					g.Structs[mangled] = st
					if g.getDropMethod(st) == "" && g.hasOwnedFields(st) {
						g.requestAutoDrop(st)
					}
					g.getEqMethod(st)
				} else if sum, ok := t.(*types.SumType); ok {
					if len(sum.TypeParams) > 0 {
						continue
					}
					g.SumTypes[mangled] = sum
					if g.getDropMethod(sum) == "" && g.hasOwnedSumFields(sum) {
						g.requestAutoDrop(sum)
					}
				} else if proto, ok := t.(*types.ProtocolType); ok {
					g.Protocols[mangled] = proto
				}
			case *ast.VarStatement:
				sym := g.SemanticInfo.Defs[s.Name]
				if sym != nil && sym.DefScope != nil && sym.DefScope.Kind == semantic.ScopePackage {
					g.Globals[g.mangleName(sym)] = sym
					if s.Value != nil {
						g.GlobalInits = append(g.GlobalInits, s)
					}
				}
			}
		}
	}

	// 1. Collect specialized types (monomorphized structs/sums) WITH type erasure
	for mangled, t := range g.SemanticInfo.SpecTypes {
		if g.isGeneric(t) {
			continue
		}
		if st, ok := t.(*types.StructType); ok {
			erasedMangled := g.getErasedTypeName(st)
			if erasedMangled != "" {
				// Check if already registered
				if _, exists := g.Structs[erasedMangled]; !exists {
					erasedSt := types.NewStructType(erasedMangled)
					erasedSt.BaseType = st.BaseType
					erasedSt.TypeArgs = make([]types.NRType, len(st.TypeArgs))
					for i := range st.TypeArgs {
						erasedSt.TypeArgs[i] = types.Ptr
					}
					erasedSt.FieldNames = append([]string(nil), st.FieldNames...)
					// Erase fields
					for fName, fType := range st.Fields {
						erasedSt.Fields[fName] = g.eraseType(fType)
					}
					g.Structs[erasedMangled] = erasedSt
					if g.getDropMethod(erasedSt) == "" && g.hasOwnedFields(erasedSt) {
						g.requestAutoDrop(erasedSt)
					}
					g.getEqMethod(erasedSt)
				}
			} else {
				g.Structs[mangled] = st
				if g.getDropMethod(st) == "" && g.hasOwnedFields(st) {
					g.requestAutoDrop(st)
				}
				g.getEqMethod(st)
			}
		} else if sum, ok := t.(*types.SumType); ok {
			erasedMangled := g.getErasedTypeName(sum)
			if erasedMangled != "" {
				if _, exists := g.SumTypes[erasedMangled]; !exists {
					erasedSum := &types.SumType{
						TypeName: erasedMangled,
						Variants: make(map[string]*types.Variant),
						Methods:  make(map[string]types.NRType),
					}
					erasedSum.BaseType = sum.BaseType
					erasedSum.TypeArgs = make([]types.NRType, len(sum.TypeArgs))
					for i := range sum.TypeArgs {
						erasedSum.TypeArgs[i] = types.Ptr
					}
					// Erase variants
					for vName, variant := range sum.Variants {
						erasedVar := &types.Variant{
							Name:       variant.Name,
							Tag:        variant.Tag,
							Fields:     make(map[string]types.NRType),
							FieldNames: append([]string(nil), variant.FieldNames...),
						}
						for fName, fType := range variant.Fields {
							erasedVar.Fields[fName] = g.eraseType(fType)
						}
						erasedSum.Variants[vName] = erasedVar
					}
					g.SumTypes[erasedMangled] = erasedSum
					if g.getDropMethod(erasedSum) == "" && g.hasOwnedSumFields(erasedSum) {
						g.requestAutoDrop(erasedSum)
					}
				}
			} else {
				g.SumTypes[mangled] = sum
				if g.getDropMethod(sum) == "" && g.hasOwnedSumFields(sum) {
					g.requestAutoDrop(sum)
				}
			}
		}
	}

	// 2. Collect monomorphized function instances WITH type erasure
	for fnStmt, instMap := range g.SemanticInfo.Instances {
		for typeKey, inst := range instMap {
			if inst.IsGenericTemplate {
				continue
			}
			sym := g.SemanticInfo.Defs[inst.Name]
			if sym == nil {
				sym = g.findDefSymbol(inst.Name.Value)
			}
			if sym == nil {
				continue
			}

			// Check if all type arguments are pointer-like
			parts := strings.Split(typeKey, "_")
			allPointerLike := true
			hasParts := false
			for _, part := range parts {
				if part == "" {
					continue
				}
				hasParts = true
				if !g.isTypeNamePointerLike(part) {
					allPointerLike = false
					break
				}
			}

			// Also check if the receiver is pointer-like
			ft, ok := sym.Type.(*types.FunctionType)
			if ok && ft.Receiver != nil {
				if g.getErasedTypeName(ft.Receiver) != "" {
					allPointerLike = true
					hasParts = true
				}
			}

			if hasParts && allPointerLike {
				// Type-erased shared monomorphization!
				// Compute erased mangled name for the function
				erasedName := g.mangleName(sym)
				if ft != nil && ft.Receiver != nil {
					erasedRec := g.getErasedTypeName(ft.Receiver)
					if erasedRec != "" {
						methodBase := inst.Name.Value
						if len(methodBase) > 9 && methodBase[len(methodBase)-9] == '_' {
							isHex := true
							for _, c := range methodBase[len(methodBase)-8:] {
								if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
									isHex = false
									break
								}
							}
							if isHex {
								methodBase = methodBase[:len(methodBase)-9]
							}
						}
						erasedName = erasedRec + "_" + methodBase
					}
				} else {
					pkgName := g.getSymbolPackage(sym)
					baseMangledName := fnStmt.Name.Value
					if pkgName != "" && pkgName != "main" {
						safePkg := strings.ReplaceAll(pkgName, "/", "_")
						safePkg = strings.ReplaceAll(safePkg, ".", "_")
						baseMangledName = safePkg + "_" + fnStmt.Name.Value
					}
					erasedName = baseMangledName + "_ptr"
				}

				if _, exists := g.Functions[erasedName]; !exists {
					erasedFT := &types.FunctionType{
						Params:        make([]types.NRType, len(ft.Params)),
						ParamLeases:   ft.ParamLeases,
						Return:        ft.Return,
						IsMethod:      ft.IsMethod,
						Receiver:      ft.Receiver,
						ReceiverLease: ft.ReceiverLease,
					}
					if ft.Receiver != nil {
						if erasedRecT := g.Structs[g.getErasedTypeName(ft.Receiver)]; erasedRecT != nil {
							erasedFT.Receiver = erasedRecT
						} else if erasedRecSum := g.SumTypes[g.getErasedTypeName(ft.Receiver)]; erasedRecSum != nil {
							erasedFT.Receiver = erasedRecSum
						}
					}
					for i, param := range ft.Params {
						erasedParam := g.eraseType(param)
						if types.IsPointerLike(param) {
							if pt, ok := erasedParam.(*types.PointerType); ok {
								if _, ok := pt.Base.(*types.StructType); ok {
									// Keep structure pointer
								} else if _, ok := pt.Base.(*types.SumType); ok {
									// Keep sum type pointer
								} else if _, ok := pt.Base.(*types.FunctionType); ok {
									// Keep function type lease
								} else {
									erasedParam = types.Ptr
								}
							} else {
								erasedParam = types.Ptr
							}
						}
						erasedFT.Params[i] = erasedParam
					}
					erasedReturn := g.eraseType(ft.Return)
					if types.IsPointerLike(ft.Return) {
						if pt, ok := erasedReturn.(*types.PointerType); ok {
							if _, ok := pt.Base.(*types.StructType); ok {
								// Keep structure pointer
							} else if _, ok := pt.Base.(*types.SumType); ok {
								// Keep sum type pointer
							} else if _, ok := pt.Base.(*types.FunctionType); ok {
								// Keep function type lease
							} else {
								erasedReturn = types.Ptr
							}
						} else {
							erasedReturn = types.Ptr
						}
					}
					erasedFT.Return = erasedReturn

					erasedSym := &semantic.Symbol{
						Name:     erasedName,
						Kind:     sym.Kind,
						Type:     erasedFT,
						DefNode:  sym.DefNode,
						DefScope: sym.DefScope,
					}
					g.Functions[erasedName] = erasedSym
				}
			} else {
				g.Functions[g.mangleName(sym)] = sym
			}
		}
	}

	// 3. Update MonomorphizedNames mapping to point to the erased name for erased function calls
	for e, name := range g.SemanticInfo.MonomorphizedNames {
		if ft, ok := g.SemanticInfo.Types[e.Function].(*types.FunctionType); ok {
			if ft.Receiver != nil {
				erasedRec := g.getErasedTypeName(ft.Receiver)
				if erasedRec != "" {
					if sel, ok := e.Function.(*ast.SelectorExpression); ok {
						methodBase := sel.Field.Value
						g.SemanticInfo.MonomorphizedNames[e] = erasedRec + "_" + methodBase
					}
				} else {
					if _, ok := e.Function.(*ast.SelectorExpression); ok {
						receiverType := ft.Receiver
						underlying := receiverType
						for {
							if pt, ok := underlying.(*types.PointerType); ok {
								underlying = pt.Base
								continue
							}
							break
						}

						pkgPrefix := ""
						for mangled, st := range g.Structs {
							if st == underlying || (st.BaseType != nil && st.BaseType == underlying) {
								if idx := strings.Index(mangled, "_"); idx != -1 {
									pkgPrefix = mangled[:idx]
									break
								}
							}
						}
						if pkgPrefix == "" {
							for mangled, sum := range g.SumTypes {
								if sum == underlying || (sum.BaseType != nil && sum.BaseType == underlying) {
									if idx := strings.Index(mangled, "_"); idx != -1 {
										pkgPrefix = mangled[:idx]
										break
									}
								}
							}
						}

						if pkgPrefix != "" && pkgPrefix != "main" && !strings.HasPrefix(name, pkgPrefix+"_") {
							g.SemanticInfo.MonomorphizedNames[e] = pkgPrefix + "_" + name
						}
					}
				}
			} else {
				for fnStmt, instMap := range g.SemanticInfo.Instances {
					for typeKey, inst := range instMap {
						sym := g.SemanticInfo.Defs[inst.Name]
						if sym == nil {
							sym = g.findDefSymbol(inst.Name.Value)
						}
						if sym != nil && g.mangleName(sym) == name {
							parts := strings.Split(typeKey, "_")
							allPointerLike := true
							hasParts := false
							for _, part := range parts {
								if part == "" {
									continue
								}
								hasParts = true
								if !g.isTypeNamePointerLike(part) {
									allPointerLike = false
									break
								}
							}
							if hasParts && allPointerLike {
								pkgName := g.getSymbolPackage(sym)
								baseMangledName := fnStmt.Name.Value
								if pkgName != "" && pkgName != "main" {
									safePkg := strings.ReplaceAll(pkgName, "/", "_")
									safePkg = strings.ReplaceAll(safePkg, ".", "_")
									baseMangledName = safePkg + "_" + fnStmt.Name.Value
								}
								g.SemanticInfo.MonomorphizedNames[e] = baseMangledName + "_ptr"
							}
						}
					}
				}
			}
		}
	}

	if g.hirProg == nil {
		lowerer := hir.NewLowerer(g.SemanticInfo, g.Solver)
		lowerer.DebugLog = g.DebugSemantic
		prog := lowerer.LowerProgram(g.Program)
		opt := optimize.NewOptimizer(g.SemanticInfo)
		g.hirProg = opt.OptimizeProgram(prog)
	}
}

func (g *Generator) hasOwnedFields(st *types.StructType) bool {
	for _, fType := range st.Fields {
		if types.IsOwnedType(fType) {
			return true
		}
	}
	return false
}

func (g *Generator) hasOwnedSumFields(st *types.SumType) bool {
	for _, variant := range st.Variants {
		for _, fType := range variant.Fields {
			if types.IsOwnedType(fType) {
				return true
			}
		}
	}
	return false
}

func (g *Generator) emitAutoDropPrototypes() {
	keys := make([]string, 0, len(g.AutoDropMethods))
	for k := range g.AutoDropMethods {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, name := range keys {
		t := g.AutoDropMethods[name]
		g.emit("void %s(%s* self);", name, g.cType(t))
	}
}

func (g *Generator) emitAutoEqPrototypes() {
	keys := make([]string, 0, len(g.AutoEqMethods))
	for k := range g.AutoEqMethods {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, name := range keys {
		t := g.AutoEqMethods[name]
		g.emit("bool %s(%s* a, %s* b);", name, g.cType(t), g.cType(t))
	}
}

func (g *Generator) isGeneric(t types.NRType) bool {
	if t == nil {
		return false
	}
	if t.GetKind() == types.KindGeneric {
		return true
	}
	if st, ok := t.(*types.StructType); ok {
		if len(st.TypeParams) > 0 {
			return true
		}
		for _, arg := range st.TypeArgs {
			if g.isGeneric(arg) {
				return true
			}
		}
	}
	if sum, ok := t.(*types.SumType); ok {
		if len(sum.TypeParams) > 0 {
			return true
		}
		for _, arg := range sum.TypeArgs {
			if g.isGeneric(arg) {
				return true
			}
		}
	}
	if pt, ok := t.(*types.PointerType); ok {
		return g.isGeneric(pt.Base)
	}
	return false
}

func (g *Generator) genFunction(sym *semantic.Symbol, fn *ast.FunctionStatement) {
	ft := sym.Type.(*types.FunctionType)
	retType := g.cType(ft.Return)
	name := g.mangleName(sym)

	var params string
	if !fn.IsExport {
		params = "void* _env_ptr"
	}

	if fn.Receiver != nil {
		t := g.cParamType(ft.Receiver, ft.ReceiverLease)
		if params != "" {
			params += ", "
		}
		params += t + " " + fn.Receiver.Name.Value
	}
	for i, p := range ft.Params {
		if params != "" {
			params += ", "
		}
		lease := types.LeaseRead
		if i < len(ft.ParamLeases) {
			lease = ft.ParamLeases[i]
		}
		t := g.cParamType(p, lease)
		params += t
		if i < len(fn.Parameters) && fn.Parameters[i].Name != nil {
			params += " " + fn.Parameters[i].Name.Value
		}
	}

	if fn.Body == nil {
		g.emit(";")
		return
	}

	g.CurrentFunc = sym
	g.emitLine(fn)
	g.emit("%s %s(%s) ", retType, name, params)

	// Open block
	g.emit("{")
	g.emitYieldCheckpoint()

	if fn.IsExport {
		g.emit("    void* _env_ptr = NULL;")
	}

	// [NEW] Add NULL check for drop methods to prevent segfaults
	if fn.Receiver != nil && strings.HasPrefix(fn.Name.Value, "drop") {
		g.emit("if (%s == NULL) return;", fn.Receiver.Name.Value)
	}

	if fn.Receiver != nil {
		sym := g.SemanticInfo.Defs[fn.Receiver.Name]
		if sym == nil {
			sym = g.SemanticInfo.Uses[fn.Receiver.Name]
		}
		if sym != nil && g.hasDropFlag(sym) {
			g.emit("    bool %s = true;", g.dropFlagName(sym))
		}
	}
	for _, param := range fn.Parameters {
		sym := g.SemanticInfo.Defs[param.Name]
		if sym == nil {
			sym = g.SemanticInfo.Uses[param.Name]
		}
		if sym != nil && g.hasDropFlag(sym) {
			g.emit("    bool %s = true;", g.dropFlagName(sym))
		}
	}

	oldBlock := g.CurrentBlock
	oldIdx := g.CurrentStmtIndex
	g.CurrentBlock = fn.Body

	g.emitDropsAt(fn.Body, 0)
	for i, stmt := range fn.Body.Statements {
		g.CurrentStmtIndex = i
		g.emitPreDropsAt(fn.Body, i)
		g.genStatement(stmt)
		g.emitDropsAt(fn.Body, i+1)
	}

	g.CurrentBlock = oldBlock
	g.CurrentStmtIndex = oldIdx

	// [NEW] If this is a 'drop' method and the receiver is owned (@T),
	// we MUST free the receiver itself at the very end.
	if fn.Receiver != nil && strings.HasPrefix(fn.Name.Value, "drop") {
		// [NEW] Drop owned fields of the struct automatically.
		// This ensures recursive drops for linked structures.
		receiverBase := types.UnwrapLease(ft.Receiver)
		// Special case: UnwrapLease doesn't unwrap @ (LeaseMove), but we need it here
		if pt, ok := ft.Receiver.(*types.PointerType); ok && pt.Kind == types.LeaseMove {
			receiverBase = pt.Base
		}

		if st, ok := receiverBase.(*types.StructType); ok {
			for _, fieldName := range st.FieldNames {
				fieldType := st.Fields[fieldName]
				g.emitDrop(fmt.Sprintf("%s->%s", fn.Receiver.Name.Value, fieldName), fieldType, true)
			}
		}

		if g.isHeapAllocated(ft.Receiver) {
			g.emit("    nr_free(%s);", fn.Receiver.Name.Value)
		}
	}

	g.emit("}")
	g.emit("")
	g.CurrentFunc = nil
	g.currentFile = ""
	g.currentLine = -1
}

func (g *Generator) emitDrop(expr string, t types.NRType, isPointerInC bool) {
	if t == nil {
		return
	}
	if !types.IsOwnedType(t) {
		return
	}

	ut := types.UnwrapLease(t)
	if pt, ok := ut.(*types.PointerType); ok && !pt.IsArray {
		ut = pt.Base
	}

	// Handle strings early
	if ut.Name() == "str" {
		g.emit("nr_free_str(%s);", expr)
		return
	}

	isList := ut.GetKind() == types.KindList

	pt, isPointer := t.(*types.PointerType)
	// Case 1: Array/List Drop
	if (isPointer && pt.IsArray) || isList {
		var elemType types.NRType
		if lt, ok := ut.(*types.ListType); ok {
			elemType = lt.ElementType
		} else if isPointer && pt.IsArray {
			elemType = pt.Base
		}

		if elemType != nil && types.IsOwnedType(elemType) {
			g.emit("{")
			g.emit("    int _len = array_count(%s);", expr)
			g.emit("    for (int _i = 0; _i < _len; _i++) {")
			elemExpr := fmt.Sprintf("((%s*)array_data(%s))[_i]", g.cType(elemType), expr)
			g.emitDrop(elemExpr, elemType, g.isPointerTypeInC(elemType))
			g.emit("    }")
			g.emit("}")
		}
		// Fall through to free the array itself if it's heap-allocated
	} else if st, ok := ut.(*types.StructType); ok {
		// Case 2: Struct Drop (Recursive-safe via function call)
		dropMethod := g.getDropMethod(t)
		if dropMethod == "" && g.hasOwnedFields(st) {
			dropMethod = g.requestAutoDrop(st)
		}

		if dropMethod != "" {
			_, isAuto := g.AutoDropMethods[dropMethod]
			if isPointerInC {
				if isAuto {
					g.emit("%s(%s);", dropMethod, expr)
				} else {
					g.emit("%s(NULL, %s);", dropMethod, expr)
				}
			} else {
				if isAuto {
					g.emit("%s(&%s);", dropMethod, expr)
				} else {
					g.emit("%s(NULL, &%s);", dropMethod, expr)
				}
			}
		}
	} else if st, ok := ut.(*types.SumType); ok {
		// Case 3: Sum Type Drop (Recursive-safe via function call)
		dropMethod := g.getDropMethod(t)
		if dropMethod == "" && g.hasOwnedSumFields(st) {
			dropMethod = g.requestAutoDrop(st)
		}

		if dropMethod != "" {
			_, isAuto := g.AutoDropMethods[dropMethod]
			if isPointerInC {
				if isAuto {
					g.emit("%s(%s);", dropMethod, expr)
				} else {
					g.emit("%s(NULL, %s);", dropMethod, expr)
				}
			} else {
				if isAuto {
					g.emit("%s(&%s);", dropMethod, expr)
				} else {
					g.emit("%s(NULL, &%s);", dropMethod, expr)
				}
			}
		}
	} else if _, ok := ut.(*types.ProtocolType); ok {
		// Case 3.5: Protocol (Interface) Drop
		// vtable[0] contains the drop function pointer for the boxed concrete data.
		if isPointerInC {
			g.emit("if (%s && %s->vtable && ((void**)%s->vtable)[0] != NULL) {", expr, expr, expr)
			g.emit("    ((void(*)(void*))((void**)%s->vtable)[0])(%s->data);", expr, expr)
			g.emit("}")
			g.emit("if (%s && %s->data) nr_free(%s->data);", expr, expr, expr)
		} else {
			g.emit("if (%s.vtable && ((void**)%s.vtable)[0] != NULL) {", expr, expr)
			g.emit("    ((void(*)(void*))((void**)%s.vtable)[0])(%s.data);", expr, expr)
			g.emit("}")
			g.emit("if (%s.data) nr_free(%s.data);", expr, expr)
		}
	} else if _, ok := ut.(*types.FunctionType); ok {
		// Case 3.7: Function (Closure) Drop
		if isPointerInC {
			g.emit("if (%s && %s->drop_fn != NULL) {", expr, expr)
			g.emit("    %s->drop_fn(%s->env);", expr, expr)
			g.emit("}")
		} else {
			g.emit("if (%s.drop_fn != NULL) {", expr)
			g.emit("    %s.drop_fn(%s.env);", expr, expr)
			g.emit("}")
		}
	} else {
		// Case 4: Individual Drop
		dropMethod := g.getDropMethod(t)
		if dropMethod != "" {
			_, isAuto := g.AutoDropMethods[dropMethod]
			if isPointerInC {
				if isAuto {
					g.emit("%s(%s);", dropMethod, expr)
				} else {
					g.emit("%s(NULL, %s);", dropMethod, expr)
				}
			} else {
				if isAuto {
					g.emit("%s(&%s);", dropMethod, expr)
				} else {
					g.emit("%s(NULL, &%s);", dropMethod, expr)
				}
			}
		}
	}

	if g.isHeapAllocated(t) {
		if ut.Name() == "str" {
			g.emit("nr_free_str(%s);", expr)
		} else if _, ok := ut.(*types.ChanType); ok {
			g.emit("channel_free(%s);", expr)
		} else if _, ok := ut.(*types.MapType); ok {
			g.emit("map_free(%s);", expr)
		} else {
			g.emit("nr_free(%s);", expr)
		}
	}
}

func (g *Generator) requestAutoDrop(t types.NRType) string {
	name := "nr_drop_" + g.mangledTypeName(t)
	if _, ok := g.AutoDropMethods[name]; !ok {
		g.AutoDropMethods[name] = t
	}
	return name
}

func (g *Generator) emitAutoDropMethods() {
	generated := make(map[string]bool)
	for {
		added := false
		// Sort keys for deterministic output
		keys := make([]string, 0, len(g.AutoDropMethods))
		for k := range g.AutoDropMethods {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		for _, name := range keys {
			if generated[name] {
				continue
			}
			generated[name] = true
			added = true

			t := g.AutoDropMethods[name]
			g.emit("void %s(%s* self) {", name, g.cType(t))
			g.emit("    if (self == NULL) return;")

			if st, ok := t.(*types.StructType); ok {
				for _, fName := range st.FieldNames {
					fType := st.Fields[fName]
					if types.IsOwnedType(fType) {
						fExpr := fmt.Sprintf("self->%s", fName)
						g.emitDrop(fExpr, fType, g.isPointerTypeInC(fType))
					}
				}
			} else if st, ok := t.(*types.SumType); ok {
				vNames := g.sortedVariantNames(st)
				emittedCount := 0
				for _, vName := range vNames {
					variant := st.Variants[vName]
					ownedFields := make([]string, 0)
					for fName, fType := range variant.Fields {
						if types.IsOwnedType(fType) {
							ownedFields = append(ownedFields, fName)
						}
					}
					if len(ownedFields) == 0 {
						continue
					}

					prefix := "if"
					if emittedCount > 0 {
						prefix = "else if"
					}
					g.emit("    %s (self->tag == %s_TAG_%s) {", prefix, g.cType(st), vName)
					for _, fName := range ownedFields {
						fType := variant.Fields[fName]
						var fExpr string
						if len(variant.Fields) == 1 {
							fExpr = fmt.Sprintf("self->data.%s", vName)
						} else {
							fExpr = fmt.Sprintf("self->data.%s.%s", vName, fName)
						}
						g.emitDrop(fExpr, fType, g.isPointerTypeInC(fType))
					}
					g.emit("    }")
					emittedCount++
				}
			}
			g.emit("}")
			g.emit("")
		}
		if !added {
			break
		}
	}
}

func (g *Generator) getDropMethod(t types.NRType) string {
	if t == nil {
		return ""
	}

	// Unwrap pointer for lookup (we want the methods on the base type)
	base := t
	if pt, ok := t.(*types.PointerType); ok {
		base = pt.Base
	}

	// Try to find the drop method in SemanticInfo
	// We check MethodSymbols which stores specialized and base methods.
	if methods, ok := g.SemanticInfo.MethodSymbols[base]; ok {
		if sym, ok := methods["drop"]; ok {
			return g.mangleName(sym)
		}
	}

	for k, methods := range g.SemanticInfo.MethodSymbols {
		if types.Equals(k, base) || (k.Name() != "" && k.Name() == base.Name()) {
			if sym, ok := methods["drop"]; ok {
				return g.mangleName(sym)
			}
		}
	}

	return ""
}

func (g *Generator) isDropMethodReceiverOwned(t types.NRType) bool {
	if t == nil {
		return false
	}
	base := t
	if pt, ok := t.(*types.PointerType); ok {
		base = pt.Base
	}

	var dropSym *semantic.Symbol
	if methods, ok := g.SemanticInfo.MethodSymbols[base]; ok {
		if sym, ok := methods["drop"]; ok {
			dropSym = sym
		}
	}
	if dropSym == nil {
		for k, methods := range g.SemanticInfo.MethodSymbols {
			if types.Equals(k, base) || (k.Name() != "" && k.Name() == base.Name()) {
				if sym, ok := methods["drop"]; ok {
					dropSym = sym
					break
				}
			}
		}
	}

	if dropSym != nil {
		if ft, ok := dropSym.Type.(*types.FunctionType); ok && ft.Receiver != nil {
			if pt, ok := ft.Receiver.(*types.PointerType); ok && pt.Kind == types.LeaseMove {
				return true
			}
		}
	}
	return false
}

func (g *Generator) getDropFunctionPointer(t types.NRType) string {
	if !types.IsOwnedType(t) {
		return "NULL"
	}

	ut := types.UnwrapLease(t)
	if pt, ok := ut.(*types.PointerType); ok && !pt.IsArray {
		ut = pt.Base
	}

	// Strings are handled specially in map_free if drop_fn is NULL,
	// but we can also pass a wrapper if we want. For now, NULL is fine for str.
	if ut.Name() == "str" {
		return "NULL"
	}

	dropMethod := g.getDropMethod(t)
	if dropMethod == "" {
		if st, ok := ut.(*types.StructType); ok && g.hasOwnedFields(st) {
			dropMethod = g.requestAutoDrop(st)
		} else if st, ok := ut.(*types.SumType); ok && g.hasOwnedSumFields(st) {
			dropMethod = g.requestAutoDrop(st)
		}
	}

	if dropMethod != "" {
		return dropMethod
	}
	return "NULL"
}

func (g *Generator) needsDrop(t types.NRType) bool {
	if t == nil {
		return false
	}
	ut := types.UnwrapLease(t)
	if ut.Name() == "str" {
		return true
	}
	if st, ok := ut.(*types.StructType); ok {
		return g.hasOwnedFields(st)
	}
	if sum, ok := ut.(*types.SumType); ok {
		return g.hasOwnedSumFields(sum)
	}
	k := ut.GetKind()
	return k == types.KindList || k == types.KindMap || k == types.KindChan || k == types.KindProtocol || k == types.KindFunction
}

func (g *Generator) hasDropFlag(sym *semantic.Symbol) bool {
	if sym == nil {
		return false
	}
	if g.CurrentLambda != nil {
		scope := g.SemanticInfo.Scopes[g.CurrentLambda]
		if scope != nil && scope.Captures != nil && scope.Captures[sym] {
			return false
		}
	}
	return (sym.Kind == semantic.SymVar || sym.Kind == semantic.SymParam) && types.IsOwnedType(sym.Type)
}

func (g *Generator) dropFlagName(sym *semantic.Symbol) string {
	return "nr_df_" + g.mangleName(sym)
}

func (g *Generator) variableName(sym *semantic.Symbol) string {
	if sym == nil {
		return ""
	}
	if g.CurrentLambda != nil && (sym.Kind == semantic.SymVar || sym.Kind == semantic.SymParam) {
		scope := g.SemanticInfo.Scopes[g.CurrentLambda]
		if scope != nil && scope.Captures != nil && scope.Captures[sym] {
			return fmt.Sprintf("_env->%s", g.mangleName(sym))
		}
	}
	return g.mangleName(sym)
}

func (g *Generator) requestAutoEq(t types.NRType) string {
	name := "nr_eq_" + g.mangledTypeName(t)
	if _, ok := g.AutoEqMethods[name]; !ok {
		g.AutoEqMethods[name] = t
	}
	return name
}

func (g *Generator) getEqMethod(t types.NRType) string {
	if t == nil {
		return ""
	}
	// Unwrap pointer for lookup (we want the methods on the base type)
	base := t
	if pt, ok := t.(*types.PointerType); ok {
		base = pt.Base
	}

	// 1. Try user-defined 'eq' method
	if methods, ok := g.SemanticInfo.MethodSymbols[base]; ok {
		if sym, ok := methods["eq"]; ok {
			return g.mangleName(sym)
		}
	}

	for k, methods := range g.SemanticInfo.MethodSymbols {
		if types.Equals(k, base) || (k.Name() != "" && k.Name() == base.Name()) {
			if sym, ok := methods["eq"]; ok {
				return g.mangleName(sym)
			}
		}
	}

	// 2. Fallback to auto-generated structural equality for structs
	if _, ok := base.(*types.StructType); ok {
		return g.requestAutoEq(base)
	}

	return ""
}

func (g *Generator) emitAutoEqMethods() {
	generated := make(map[string]bool)
	for {
		added := false
		keys := make([]string, 0, len(g.AutoEqMethods))
		for k := range g.AutoEqMethods {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		for _, name := range keys {
			if generated[name] {
				continue
			}
			generated[name] = true
			added = true

			t := g.AutoEqMethods[name]
			g.emit("bool %s(%s* a, %s* b) {", name, g.cType(t), g.cType(t))
			g.emit("    if (a == b) return true;")
			g.emit("    if (a == NULL || b == NULL) return false;")

			if st, ok := t.(*types.StructType); ok {
				for _, fName := range st.FieldNames {
					fType := st.Fields[fName]
					ut := types.UnwrapLease(fType)

					eqCall := ""
					if _, isStruct := ut.(*types.StructType); isStruct {
						eqMethod := g.getEqMethod(ut)
						args := ""
						if !strings.HasPrefix(eqMethod, "nr_eq_") {
							args = "NULL, "
						}
						if g.isPointerTypeInC(fType) {
							eqCall = fmt.Sprintf("!%s(%sa->%s, b->%s)", eqMethod, args, fName, fName)
						} else {
							eqCall = fmt.Sprintf("!%s(%s&(a->%s), &(b->%s))", eqMethod, args, fName, fName)
						}
					} else if ut.Name() == "str" {
						eqCall = fmt.Sprintf("!nr_str_eq(a->%s, b->%s)", fName, fName)
					} else if pt, ok := ut.(*types.PointerType); ok && !pt.IsArray {
						// For pointers, we compare values if it's a struct pointer, else reference
						if _, isStruct := pt.Base.(*types.StructType); isStruct {
							eqMethod := g.getEqMethod(pt.Base)
							args := ""
							if !strings.HasPrefix(eqMethod, "nr_eq_") {
								args = "NULL, "
							}
							eqCall = fmt.Sprintf("!%s(%sa->%s, b->%s)", eqMethod, args, fName, fName)
						} else {
							eqCall = fmt.Sprintf("a->%s != b->%s", fName, fName)
						}
					} else if _, isFunc := ut.(*types.FunctionType); isFunc {
						eqCall = fmt.Sprintf("(a->%s.env != b->%s.env || a->%s.fn_ptr != b->%s.fn_ptr)", fName, fName, fName, fName)
					} else if _, isProto := ut.(*types.ProtocolType); isProto {
						if g.isPointerTypeInC(fType) {
							eqCall = fmt.Sprintf("(a->%s->data != b->%s->data || a->%s->vtable != b->%s->vtable)", fName, fName, fName, fName)
						} else {
							eqCall = fmt.Sprintf("(a->%s.data != b->%s.data || a->%s.vtable != b->%s.vtable)", fName, fName, fName, fName)
						}
					} else {
						eqCall = fmt.Sprintf("a->%s != b->%s", fName, fName)
					}
					g.emit("    if (%s) return false;", eqCall)
				}
			}
			g.emit("    return true;")
			g.emit("}")
			g.emit("")
		}
		if !added {
			break
		}
	}
}

func (g *Generator) emitGlobalInits() {
	g.emit("// --- GLOBAL INITIALIZERS ---")
	g.emit("void nr_init_globals(void) {")
	for _, s := range g.GlobalInits {
		sym := g.SemanticInfo.Defs[s.Name]
		if sym == nil {
			continue
		}
		name := g.mangleName(sym)
		g.emitLine(s)
		g.buf.WriteString(fmt.Sprintf("    %s = ", name))
		g.genExpression(s.Value)
		g.emit(";")
	}
	g.emit("}")
	g.currentFile = ""
	g.currentLine = -1
}

func (g *Generator) emitGlobalCleanups() {
	g.emit("void nr_cleanup_globals(void) {")
	for i := len(g.GlobalInits) - 1; i >= 0; i-- {
		s := g.GlobalInits[i]
		sym := g.SemanticInfo.Defs[s.Name]
		if sym == nil {
			continue
		}
		if types.IsOwnedType(sym.Type) {
			name := g.mangleName(sym)
			isPtr := g.isSymbolPointerInC(sym)
			g.emitDrop(name, sym.Type, isPtr)
		}
	}
	g.emit("}")
	g.emit("")
	g.emit("void nr_cleanup_globals(void);")
	g.emit("")
}

func (g *Generator) requestVTable(t types.NRType, p *types.ProtocolType) string {
	sanitizedName := t.Name()

	// Sanitize any characters that are invalid in C identifiers
	r := strings.NewReplacer(
		"@", "",
		"#", "",
		"&", "",
		"(", "_",
		")", "_",
		"[", "_",
		"]", "_",
		"*", "_ptr_",
		" ", "_",
		",", "_",
		".", "_",
	)
	sanitizedName = r.Replace(sanitizedName)
	sanitizedName = strings.Trim(sanitizedName, "_")

	key := fmt.Sprintf("%s_%s", sanitizedName, p.ProtocolName)
	if _, ok := g.VTables[key]; !ok {
		g.VTables[key] = VTableInstance{Type: t, Protocol: p}
	}
	return "vtable_" + key
}

func (g *Generator) emitVTables() {
	if len(g.VTables) == 0 {
		return
	}
	g.emit("// --- VTABLES ---")
	for key, inst := range g.VTables {
		vtableName := "vtable_" + key
		if g.MultiFileMode {
			g.emit("void* %s[] = {", vtableName)
		} else {
			g.emit("static void* %s[] = {", vtableName)
		}

		dropFn := g.getDropFunctionPointer(inst.Type)
		g.emit("    (void*)%s,", dropFn)

		// Sort method names to match protocol order (replicated from analyzer/prototypes)
		methodNames := []string{}
		for name := range inst.Protocol.Methods {
			methodNames = append(methodNames, name)
		}
		sort.Strings(methodNames)

		for _, mName := range methodNames {
			concreteMethod := g.findConcreteMethod(inst.Type, mName)
			g.emit("    (void*)%s,", concreteMethod)
		}
		g.emit("};")
		g.emit("")
	}
}

func (g *Generator) findConcreteMethod(t types.NRType, mName string) string {
	ut := types.UnwrapLease(t)

	// Check semantic info for monomorphized methods first
	if methods, ok := g.SemanticInfo.MethodSymbols[ut]; ok {
		if sym, ok := methods[mName]; ok {
			return g.mangleName(sym)
		}
	}

	for k, methods := range g.SemanticInfo.MethodSymbols {
		if types.Equals(k, ut) || (k.Name() != "" && k.Name() == ut.Name()) {
			if sym, ok := methods[mName]; ok {
				return g.mangleName(sym)
			}
		}
	}

	// Fallback for simple types or if symbol is not found
	sanitizedName := ut.Name()
	sanitizedName = strings.TrimPrefix(strings.TrimPrefix(strings.TrimPrefix(sanitizedName, "@"), "#"), "&")
	return sanitizedName + "_" + mName
}

func (g *Generator) registerStringLiteral(val string) string {
	if name, exists := g.StringLiterals[val]; exists {
		return name
	}
	name := fmt.Sprintf("_str_lit_%d", len(g.StringLiterals)+1)
	g.StringLiterals[val] = name
	return name
}

func (g *Generator) escapeStringForC(s string) string {
	var buf strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '"' {
			if i > 0 && s[i-1] == '\\' {
				buf.WriteByte(c)
			} else {
				buf.WriteString(`\"`)
			}
		} else if c == '\n' {
			buf.WriteString(`\n`)
		} else if c == '\r' {
			buf.WriteString(`\r`)
		} else if c == '\t' {
			buf.WriteString(`\t`)
		} else {
			buf.WriteByte(c)
		}
	}
	return buf.String()
}

func (g *Generator) emitStringLiterals() {
	if len(g.StringLiterals) == 0 {
		return
	}

	type litItem struct {
		val  string
		name string
	}
	var items []litItem
	for val, name := range g.StringLiterals {
		items = append(items, litItem{val, name})
	}
	sort.Slice(items, func(i, j int) bool {
		return items[i].name < items[j].name
	})

	g.emit("// Global Static String Literals")
	for _, item := range items {
		escaped := g.escapeStringForC(item.val)
		size := len(item.val) + 1
		g.emit("static const struct { nr_header_t h; char data[%d]; } %s = { {(int32_t)%d, 1, NR_MAGIC_STATIC, 1, \"literal\", 0, NULL, NULL}, \"%s\" };", size, item.name, size-1, escaped)
	}
	g.emit("")
}

func (g *Generator) CollectDefinitions() {
	g.collectDefinitions()
}

func (g *Generator) GeneratePackageCode(pkgName string) (string, error) {
	g.buf.Reset()
	g.StringLiterals = make(map[string]string)
	g.SpawnStructs = nil
	g.SpawnWrappers = nil
	g.GeneratedLambdas = make(map[string]bool)

	// Lower AST to HIR
	if g.hirProg == nil {
		lowerer := hir.NewLowerer(g.SemanticInfo, g.Solver)
		lowerer.DebugLog = g.DebugSemantic
		prog := lowerer.LowerProgram(g.Program)
		opt := optimize.NewOptimizer(g.SemanticInfo)
		g.hirProg = opt.OptimizeProgram(prog)
	}
	hirProg := g.hirProg
	hirFuncs := make(map[string]*hir.Function)
	for _, hf := range hirProg.Functions {
		hirFuncs[g.mangleName(hf.FuncSymbol)] = hf
	}

	g.emit("// Package %s", pkgName)
	g.emit("// [DEBUG] len(hirProg.Functions) = %d", len(hirProg.Functions))
	for _, hf := range hirProg.Functions {
		g.emit("// [DEBUG] hf: name=%s, isLambda=%v, pkg=%s", hf.Name, hf.LambdaExpr != nil, g.getHIRFunctionPackage(hf))
	}
	g.emit("#include \"out.h\"")
	g.emit("")

	// Emit package-level global definitions
	g.emitPackageGlobalDefs(pkgName)

	// Generate all functions into a temporary buffer first
	funcBuf := new(bytes.Buffer)
	mainBuf := g.buf
	g.buf = funcBuf

	// Loop through sorted function names and emit functions belonging to this package
	for _, name := range g.sortedFunctionNames() {
		sym := g.Functions[name]
		if sym.DefNode == nil {
			continue
		}

		// Check package name
		if g.getSymbolPackage(sym) != pkgName {
			continue
		}

		fn, ok := sym.DefNode.(*ast.FunctionStatement)
		if !ok || ast.GetAttribute(fn.Attributes, "macro") != nil || fn.Body == nil {
			continue
		}
		if hf, ok := hirFuncs[name]; ok {
			g.genHIRFunction(hf)
		} else {
			g.genFunction(sym, fn)
		}
	}

	// Compile lowered lambda functions belonging to this package
	for _, hf := range hirProg.Functions {
		if hf.LambdaExpr != nil {
			if g.getHIRFunctionPackage(hf) == pkgName {
				g.genHIRFunction(hf)
			}
		}
	}

	// Restore main buffer
	g.buf = mainBuf

	// Emit package-specific static string literals (now populated!)
	g.emitStringLiterals()

	// Emit package-specific static spawn structs & wrappers (now populated!)
	for _, s := range g.SpawnStructs {
		g.emit(s)
	}
	for _, s := range g.SpawnWrappers {
		g.emit(s)
	}

	// Emit package-specific static lambda environment drop functions
	g.emitPackageLambdaEnvDrops(pkgName)

	// Finally append the compiled functions
	g.buf.Write(funcBuf.Bytes())

	return g.buf.String(), nil
}

func (g *Generator) GenerateHeader() (string, error) {
	g.buf.Reset()
	g.emit("// Generated by Nora Compiler Contract Header")
	g.emit("#ifndef NORA_OUT_H")
	g.emit("#define NORA_OUT_H")
	g.emit("")

	// Emit native headers requested by dependencies
	for _, hdr := range g.NativeHeaders {
		g.emit(fmt.Sprintf("#include \"%s\"", hdr))
	}
	g.emit("")

	// Emit Runtime Components
	g.emitRuntime()

	// Emit Type Forward Declarations
	g.emitForwardDeclarations()

	// Emit Protocol Definitions
	g.emitProtocolDefs()

	// Emit Topologically Sorted Type Definitions
	g.emitCombinedTypeDefs()

	// Emit Lambda Environment Struct Definitions
	g.emitLambdaEnvDefs()

	// Emit Prototypes
	for _, file := range g.Program.Files {
		g.emitExternPrototypes(file)
	}
	g.emitPrototypes()

	// Emit Global Variable Declarations (extern)
	g.emitGlobalDecls()

	// Emit Prototypes for Auto-Generated Drop Methods
	g.emitAutoDropPrototypes()
	// Emit Prototypes for Auto-Generated Equality Methods
	g.emitAutoEqPrototypes()

	// Emit VTable Declarations
	g.emitVTableDecls()

	g.emit("#endif // NORA_OUT_H")
	return g.buf.String(), nil
}

func (g *Generator) GenerateSharedGlobals() (string, error) {
	g.buf.Reset()
	g.emit("// Shared Globals, drop methods, equality methods, and vtables")
	g.emit("#include \"out.h\"")
	g.emit("")

	// Emit Auto-Generated Drop Methods
	g.emitAutoDropMethods()

	// Emit Auto-Generated Equality Methods
	g.emitAutoEqMethods()

	// Emit Global Initializers
	g.emitGlobalInits()

	// Emit VTables
	g.emitVTables()

	// Emit Global Cleanups
	g.emitGlobalCleanups()

	// Emit Main Wrapper
	mainName := "main" // Default Nora main
	for _, sym := range g.Functions {
		if sym.Name == "main" {
			mainName = g.mangleName(sym)
			break
		}
	}
	platform := g.GetTarget()
	g.emit(platform.GetMainWrapper(mainName))

	return g.buf.String(), nil
}

func (g *Generator) emitVTableDecls() {
	if len(g.VTables) == 0 {
		return
	}
	g.emit("// --- VTABLE DECLARATIONS ---")
	for key := range g.VTables {
		vtableName := "vtable_" + key
		g.emit("extern void* %s[];", vtableName)
	}
}

func (g *Generator) emitPackageGlobalDefs(pkgName string) {
	for _, sym := range g.Globals {
		if g.getSymbolPackage(sym) == pkgName {
			g.emit("%s %s;", g.cType(sym.Type), g.mangleName(sym))
		}
	}
}

func (g *Generator) generateLambdaFunction(e *ast.LambdaExpression) string {
	oldLambda := g.CurrentLambda
	g.CurrentLambda = e
	oldNoTemp := g.NoTempWrap
	g.NoTempWrap = false
	defer func() {
		g.CurrentLambda = oldLambda
		g.NoTempWrap = oldNoTemp
	}()

	t := g.SemanticInfo.Types[e]
	ft, _ := t.(*types.FunctionType)

	h := sha256.New()
	h.Write([]byte(filepath.Base(e.Pos().Filename)))
	h.Write([]byte(fmt.Sprintf(":%d:%d", e.Pos().Line, e.Pos().Column)))
	if ft != nil {
		h.Write([]byte(fmt.Sprintf("%v", ft)))
	}
	if g.CurrentFunc != nil {
		h.Write([]byte(g.CurrentFunc.Name))
	}
	hashVal := hex.EncodeToString(h.Sum(nil))[:8]
	fnName := fmt.Sprintf("nr_lambda_%s", hashVal)
	if g.GeneratedLambdas[fnName] {
		return fnName
	}
	g.GeneratedLambdas[fnName] = true
	envStructName := fnName + "_env_t"

	scope := g.SemanticInfo.Scopes[e]

	var captures []*semantic.Symbol
	if scope != nil && scope.Captures != nil {
		for sym := range scope.Captures {
			captures = append(captures, sym)
		}
	}

	sort.Slice(captures, func(i, j int) bool {
		return captures[i].Name < captures[j].Name
	})

	var envDef bytes.Buffer
	inHeader := false
	if g.MultiFileMode && g.hirProg != nil {
		for _, hf := range g.hirProg.Functions {
			if hf.Name == fnName {
				inHeader = true
				break
			}
		}
	}
	if !inHeader {
		envDef.WriteString(fmt.Sprintf("typedef struct {\n"))
		for _, cap := range captures {
			envDef.WriteString(fmt.Sprintf("    %s %s;\n", g.cType(cap.Type), g.mangleName(cap)))
		}
		envDef.WriteString(fmt.Sprintf("} %s;\n\n", envStructName))
	}

	// Generate a custom drop function for the environment struct
	envDef.WriteString(fmt.Sprintf("void %s_env_drop(void* env_ptr) {\n", fnName))
	envDef.WriteString(fmt.Sprintf("    if (!env_ptr) return;\n"))
	envDef.WriteString(fmt.Sprintf("    %s* env = (%s*)env_ptr;\n", envStructName, envStructName))

	// Temporarily redirect buffer to envDef to generate recursive drops for captured owned fields
	oldBuf := g.buf
	g.buf = &envDef
	oldDebug := g.EnableDebug
	g.EnableDebug = false
	for _, cap := range captures {
		if types.IsOwnedType(cap.Type) {
			fieldExpr := fmt.Sprintf("env->%s", g.mangleName(cap))
			g.emitDrop(fieldExpr, cap.Type, g.isPointerTypeInC(cap.Type))
		}
	}
	g.EnableDebug = oldDebug
	g.emit("    nr_free(env);\n")
	g.emit("}\n\n")
	g.buf = oldBuf

	g.SpawnStructs = append(g.SpawnStructs, envDef.String())

	var fnDef bytes.Buffer
	t = g.SemanticInfo.Types[e]
	ft = t.(*types.FunctionType)

	fnDef.WriteString(fmt.Sprintf("%s %s(void* _env_ptr", g.cType(ft.Return), fnName))
	for i, p := range ft.Params {
		fnDef.WriteString(", ")
		lease := types.LeaseRead
		if i < len(ft.ParamLeases) {
			lease = ft.ParamLeases[i]
		}
		fnDef.WriteString(g.cParamType(p, lease))
		if i < len(e.Parameters) && e.Parameters[i].Name != nil {
			fnDef.WriteString(" ")
			fnDef.WriteString(e.Parameters[i].Name.Value)
		}
	}
	fnDef.WriteString(") {\n")
	fnDef.WriteString(fmt.Sprintf("    %s* _env = (%s*)_env_ptr;\n", envStructName, envStructName))

	oldBuf = g.buf
	g.buf = &fnDef

	for _, param := range e.Parameters {
		if param.Name != nil {
			sym := g.SemanticInfo.Defs[param.Name]
			if sym == nil {
				sym = g.SemanticInfo.Uses[param.Name]
			}
			if sym != nil && g.hasDropFlag(sym) {
				g.emit("    bool %s = true;", g.dropFlagName(sym))
			}
		}
	}

	fakeSym := &semantic.Symbol{
		Name: fnName,
		Type: ft,
	}
	oldFunc := g.CurrentFunc
	g.CurrentFunc = fakeSym

	oldBlock := g.CurrentBlock
	oldIdx := g.CurrentStmtIndex
	g.CurrentBlock = e.Body

	g.emitDropsAt(e.Body, 0)
	for i, stmt := range e.Body.Statements {
		g.CurrentStmtIndex = i
		g.emitPreDropsAt(e.Body, i)
		g.genStatement(stmt)
		g.emitDropsAt(e.Body, i+1)
	}

	g.CurrentBlock = oldBlock
	g.CurrentStmtIndex = oldIdx
	g.CurrentFunc = oldFunc
	g.buf = oldBuf

	fnDef.WriteString("}\n")

	g.SpawnWrappers = append(g.SpawnWrappers, fnDef.String())

	return fnName
}

func (g *Generator) populateLambdaEnv(e *ast.LambdaExpression, scope *semantic.Scope) {
	var captures []*semantic.Symbol
	if scope != nil && scope.Captures != nil {
		for sym := range scope.Captures {
			captures = append(captures, sym)
		}
	}
	sort.Slice(captures, func(i, j int) bool {
		return captures[i].Name < captures[j].Name
	})

	for _, cap := range captures {
		name := g.mangleName(cap)
		rhs := name
		if g.CurrentLambda != nil {
			parentScope := g.SemanticInfo.Scopes[g.CurrentLambda]
			if parentScope != nil && parentScope.Captures != nil && parentScope.Captures[cap] {
				rhs = fmt.Sprintf("_env->%s", name)
			}
		}
		g.buf.WriteString(fmt.Sprintf("_env_local->%s = %s; ", name, rhs))
	}
}

func (g *Generator) getHIRFunctionPackage(hf *hir.Function) string {
	if hf.FuncSymbol != nil {
		if pkg := g.getSymbolPackage(hf.FuncSymbol); pkg != "" {
			return pkg
		}
	}
	if hf.LambdaExpr != nil {
		filename, err1 := filepath.Abs(hf.LambdaExpr.Pos().Filename)
		for _, file := range g.Program.Files {
			absName, err2 := filepath.Abs(file.Name)
			if err1 == nil && err2 == nil && absName == filename {
				return g.getPackageName(file)
			}
		}
	}
	return ""
}

func (g *Generator) emitLambdaEnvDefs() {
	if g.hirProg == nil {
		return
	}
	for _, hf := range g.hirProg.Functions {
		if hf.LambdaExpr != nil {
			fnName := hf.Name
			envStructName := fnName + "_env_t"
			scope := g.SemanticInfo.Scopes[hf.LambdaExpr]
			hasCaptures := false
			if scope != nil && scope.Captures != nil && len(scope.Captures) > 0 {
				hasCaptures = true
			}
			if hasCaptures {
				var captures []*semantic.Symbol
				for sym := range scope.Captures {
					captures = append(captures, sym)
				}
				sort.Slice(captures, func(i, j int) bool {
					return captures[i].Name < captures[j].Name
				})

				g.emit(fmt.Sprintf("typedef struct {"))
				for _, cap := range captures {
					g.emit(fmt.Sprintf("    %s %s;", g.cType(cap.Type), g.mangleName(cap)))
				}
				g.emit(fmt.Sprintf("} %s;", envStructName))
				g.emit(fmt.Sprintf("void %s_env_drop(void* env_ptr);", fnName))
				g.emit("")
			}
		}
	}
}

func (g *Generator) emitLambdaEnvDrops() {
	if g.hirProg == nil {
		return
	}
	for _, hf := range g.hirProg.Functions {
		if hf.LambdaExpr != nil {
			fnName := hf.Name
			envStructName := fnName + "_env_t"
			scope := g.SemanticInfo.Scopes[hf.LambdaExpr]
			hasCaptures := false
			if scope != nil && scope.Captures != nil && len(scope.Captures) > 0 {
				hasCaptures = true
			}
			if hasCaptures {
				var captures []*semantic.Symbol
				for sym := range scope.Captures {
					captures = append(captures, sym)
				}
				sort.Slice(captures, func(i, j int) bool {
					return captures[i].Name < captures[j].Name
				})

				g.emit(fmt.Sprintf("void %s_env_drop(void* env_ptr) {", fnName))
				g.emit("    if (!env_ptr) return;")
				g.emit(fmt.Sprintf("    %s* env = (%s*)env_ptr;", envStructName, envStructName))
				for _, cap := range captures {
					if types.IsOwnedType(cap.Type) {
						fieldExpr := fmt.Sprintf("env->%s", g.mangleName(cap))
						g.emitDrop(fieldExpr, cap.Type, g.isPointerTypeInC(cap.Type))
					}
				}
				g.emit("    nr_free(env);")
				g.emit("}")
				g.emit("")
			}
		}
	}
}

func (g *Generator) emitPackageLambdaEnvDrops(pkgName string) {
	if g.hirProg == nil {
		return
	}
	for _, hf := range g.hirProg.Functions {
		if hf.LambdaExpr != nil && g.getHIRFunctionPackage(hf) == pkgName {
			fnName := hf.Name
			envStructName := fnName + "_env_t"
			scope := g.SemanticInfo.Scopes[hf.LambdaExpr]
			hasCaptures := false
			if scope != nil && scope.Captures != nil && len(scope.Captures) > 0 {
				hasCaptures = true
			}
			if hasCaptures {
				var captures []*semantic.Symbol
				for sym := range scope.Captures {
					captures = append(captures, sym)
				}
				sort.Slice(captures, func(i, j int) bool {
					return captures[i].Name < captures[j].Name
				})

				g.emit(fmt.Sprintf("void %s_env_drop(void* env_ptr) {", fnName))
				g.emit("    if (!env_ptr) return;")
				g.emit(fmt.Sprintf("    %s* env = (%s*)env_ptr;", envStructName, envStructName))
				for _, cap := range captures {
					if types.IsOwnedType(cap.Type) {
						fieldExpr := fmt.Sprintf("env->%s", g.mangleName(cap))
						g.emitDrop(fieldExpr, cap.Type, g.isPointerTypeInC(cap.Type))
					}
				}
				g.emit("    nr_free(env);")
				g.emit("}")
				g.emit("")
			}
		}
	}
}
